-- Миграция для исправления некорректных значений datetime
-- Дата: 2024-01-XX
-- Описание: Исправляет значения '0000-00-00' в полях created_at и updated_at

USE oneui_hub;

SET SQL_SAFE_UPDATES = 0;

-- Устанавливаем правильный SQL режим
SET sql_mode = 'TRADITIONAL,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO';

UPDATE models 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE models 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE model_configs 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE model_configs 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE companies 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE companies 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE users 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE users 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE rate_limits 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE rate_limits 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE api_keys 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE requests 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE budgets 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

UPDATE budgets 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE exchange_rates 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE user_spendings 
SET updated_at = CURRENT_TIMESTAMP 
WHERE updated_at = '0000-00-00 00:00:00' OR updated_at IS NULL;

UPDATE tiers 
SET created_at = CURRENT_TIMESTAMP 
WHERE created_at = '0000-00-00 00:00:00' OR created_at IS NULL;

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE models 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Конфигурации моделей
ALTER TABLE model_configs 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Компании
ALTER TABLE companies 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE users 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE rate_limits 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE api_keys 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE requests 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE budgets 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE exchange_rates 
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE user_spendings 
MODIFY COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE tiers 
MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

COMMIT; 